# services:  
#   db:
#     image: postgres
#     environment:
#       - POSTGRES_USER=${POSTGRES_USER}
#       - POSTGRES_DB=${POSTGRES_DB}
#       - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#     ports:
#       - "5432:5432"

version: '3'
services:
  redis:
    image: redis:6
    container_name: redis
    restart: on-failure
    ports:
      - '6379:6379'

  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    shm_size: 1g
    container_name: db
    restart: on-failure
    volumes:
      - ./:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data:rw
    env_file:
      - .env
    ports:
      - '5432:5432'

volumes:
  db: