# Generated by Django 5.0.3 on 2024-05-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_employee_department_alter_employee_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
