# Generated by Django 5.0.3 on 2024-03-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
