# Generated by Django 5.0.3 on 2024-03-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='adress',
            new_name='address',
        ),
    ]
