# Generated by Django 5.0.3 on 2024-05-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
