# Generated by Django 5.0.3 on 2024-05-20 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_finished_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='finished_at',
            new_name='completion_date',
        ),
    ]
