# Generated by Django 5.0.3 on 2024-03-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('store', '0002_rename_adress_store_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stores',
            field=models.ManyToManyField(blank=True, through='product.Inventory', to='store.store'),
        ),
    ]
