# Generated by Django 5.0.3 on 2024-04-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_stores'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='This is a category', max_length=255),
            preserve_default=False,
        ),
    ]
